name: 👀 release

on:
  workflow_dispatch:
    inputs:
      bump:
        type: choice

        description: Semver version to bump

        options:
          - patch

          - minor

          - major

        default: patch

      dry-run:
        type: boolean

        description: Perform dry-run

        default: true

defaults:
  run:
    shell: bash

permissions:
  contents: write

  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3

        with:
          node-version: "18.x"

          registry-url: "https://registry.npmjs.org"

      - run: npm install -g npm

      - run: npm i

      - uses: chainguard-dev/actions/setup-gitsign@f5a6616ce43b6ffabeddb87480a13721fffb3588

      - name: Set up Git user

        run: |

          git config --local user.name "sebastianjnuwu"

          # This email identifies the commit as GitHub Actions - see https://github.com/orgs/community/discussions/26560

          git config --local user.email "sebastianjnuwu@gmail.com"

      - run: npm run release ${{ github.event.inputs.bump }}${{ github.event.inputs.dry-run == 'true' && ' -- --dry-run' || '' }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
